/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc;

//import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import java.sql.Statement;

import java.sql.ResultSet;

//import java.sql.*;

public class App {

    public static void main(String[] args) throws Exception {

        String sql = "select c.first_name, c.last_name, f.title from customer as c"
                + " inner join payment as p"
                + " on c.customer_id= p.customer_id"
                + " inner join rental as r"
                + " on  p.rental_id=r.rental_id"
                + " inner join inventory as i"
                + " on r.inventory_id=i.inventory_id"
                + " inner join film as f"
                + " on i.film_id=f.film_id"
                + " where p.amount=0";
        Connection connection = null;
        String url = "jdbc:mysql://51.68.227.19:3306/florin";
        String user = "M2I";
        String password = "H3ll0M2I";

        try {
            connection = DriverManager.getConnection(url, user, password);
            if (connection != null) {
                System.out.println("Connected to the database");
            }
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(sql);

            while (result.next()) {
                // InputStream stream = result.getBinaryStream(1);
                // System.out.println(stream);
                // String first_name = result.getString("first_name");
                // String last_name = result.getString("last_name");
                java.sql.Array objet = result.getArray("last_name");

                // String title = result.getString("title");
                // System.out.println(result.getString("title"));
                // System.out.println(first_name + " " + last_name + " : " + title);
                // System.out.println(result.getString("description"));

                System.out.println(objet);

            }

        } catch (SQLException ex) {
            System.out.println("SQLException:" + ex.getMessage());
            System.out.println("SQLState:" + ex.getSQLState());
            System.out.println("VendorError:" + ex.getErrorCode());
            // System.out.println("An error occurred. Maybe user/password is invalid");
            // ex.printStackTrace();
        }
    }
}
